version: '3.8'

services:
  neuroai-dashboard:
    build:
      context: ../..
      dockerfile: setup_config/docker/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ../../:/app
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_HEADLESS=true
    restart: unless-stopped
    container_name: neuroai-dashboard
